name: sky_tools
version: 0.0.9
description: Tools for building Sky applications
homepage: https://github.com/domokit/sky_tools
author: Chromium Authors <sky-dev@googlegroups.com>

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  args: ^0.13.0
  mustache4dart: ^1.0.0
  path: ^1.3.0
  shelf: ^0.6.2
  shelf_static: ^0.2.3
<<<<<<< HEAD
  shelf_route: ^0.13.4

dev_dependencies:
  test: ^0.12.0
=======
  test: ">=0.12.4+5 <0.12.5"
>>>>>>> 01afe5a6126 (Update loadVMFileHook to the real location)

executables:
  sky_tools:
