name: cassowary
description: Cassowary Constraint Solving Toolkit
version: 0.1.7
author: Flutter Authors <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/flutter/tree/master/packages/cassowary
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  test_runner: '<=0.2.16'
  dart_coveralls: '<=0.3.0'
